[package]
name = "termwebbrowser"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
serde_json = "1.0.133"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
